### ISSUE TITLE
When there are no publishers, the publishers tab fails with error

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#114] opened 2018-11-07 13:42 UTC
![image](https://user-images.githubusercontent.com/718827/48134764-3f9f1a80-e29b-11e8-978a-87241a486213.png)
![image](https://user-images.githubusercontent.com/718827/48134795-56de0800-e29b-11e8-84a6-61c7c1037ab9.png)

**Comment by skodapetr** [comment] 2018-11-08 11:51
I'm unable to reproduce without the data. 

The log message is meaningless as it does not point to the original source.

**Comment by skodapetr** [comment] 2018-11-12 09:53
Should be fixed by 07f4f18caeb6cbee982f4e0326953ccc4f3a64ed

**Closed as completed** 2018-11-12 11:44 UTC
Labels: bug
